[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
solc_version = "0.8.13"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20_000

[profile.ci]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config